bump_version: null
lint:
  actions_ci: false
  files_unchanged:
    - .github/workflows/linting.yml
    - .github/CONTRIBUTING.md
  multiqc_config: false
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Athanasios Baltzis, Jose Espinosa-Carrasco, Harshil Patel
  description: Protein 3D structure prediction pipeline
  force: false
  is_nfcore: true
  name: proteinfold
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - igenomes
  version: 1.2.0dev
update: null
