contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #proteinfold channel"
    url: https://nfcore.slack.com/channels/proteinfold
    about: Discussion about the nf-core/proteinfold pipeline
