FROM ghcr.io/sokrypton/colabfold:1.5.5-cuda12.2.2

RUN wget https://mmseqs.com/latest/mmseqs-linux-gpu.tar.gz && \
    tar xvfz mmseqs-linux-gpu.tar.gz && \
    mv mmseqs/bin/* /usr/local/bin/ && \
    rm -rf mmseqs-linux-*.tar.gz mmseqs
