name: nf-core AWS full size tests
# This workflow is triggered on published releases.
# It can be additionally triggered manually with GitHub actions workflow dispatch button.
# It runs the -profile 'test_full' on AWS batch

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  run-platform:
    name: Run AWS full tests
    if: github.repository == 'nf-core/proteinfold'
    runs-on: ubuntu-latest
    # Do a full-scale run on each of the mode
    strategy:
      matrix:
        mode:
          [
            "alphafold2_standard",
            "alphafold2_split",
            "alphafold2_multimer",
            "colabfold_local",
            "colabfold_webserver",
            "colabfold_multimer",
            "esmfold",
            "esmfold_multimer",
          ]
    steps:
      - name: Launch workflow via Seqera Platform
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          revision: ${{ github.sha }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/proteinfold/work-${{ github.sha }}
          parameters: |
            {
              "hook_url": "${{ secrets.MEGATESTS_ALERTS_SLACK_HOOK_URL }}",
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/proteinfold/results-${{ github.sha }}/mode_${{ matrix.mode }}"
            }
          profiles: test_full_${{ matrix.mode }}

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Seqera Platform debug log file
          path: |
            seqera_platform_action_*.log
            seqera_platform_action_*.json
